
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api-app
spec:
  selector:
    matchLabels:
      name: api-app
  replicas: 1
  template:
    metadata:
      labels:
        name: api-app
    spec:
      containers:
      - name: api-app
        image: eijinaka2021/epoch-sample-api2:master.20220509-133607
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: FLASK_ENV
          value: "development"
        - name: API_PORT
          value: "8000"
        - name: PYTHONIOENCODING
          value: utf-8
  strategy:
    blueGreen:
      activeService: api-app
      previewService: api-app-preview
      scaleDownDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: api-app-preview
  labels:
    name: api-app-preview
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    name: api-app
---

apiVersion: v1
kind: Service
metadata:
  name: api-app
  labels:
    name: api-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 31002
  selector:
    name: api-app
